name: Build java and Angular and push Docker image

on:
  workflow_dispatch:
    inputs:
      versao:
        description: 'Versão do App'
        required: true
        default: '1.0.0'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: BUILD

    steps:
      - name: Valida Versão da tag
        run: |
          VERSAO="${{ github.event.inputs.versao }}"
          if [[ !"$VERSAO" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Versão inválida. Use o formato X.Y.Z (ex: 1.0.0)."
            exit 1
          fi
          echo "Versão válida: $VERSAO"
      
      - name: Valida versão no DockerHub
        run: |
          VERSAO="${{ github.event.inputs.versao }}"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/${{ github.repository }}/tags/${VERSAO}/")
          if [ "$RESPONSE" -eq 200 ]; then
            echo "Tag $VERSAO já existe no DockerHub."
            exit 1
          else
            echo "Tag $VERSAO não existe no DockerHub. Prosseguindo com o build."
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './src/frontend/web-todo/package-lock.json'
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Update Versão Pom.xml
        run: |
          VERSAO="${{ github.event.inputs.versao }}"
          mvn versions:set -DnewVersion=$VERSAO
          mvn versions:commit

      - name: Build with Maven
        run: mvn clean package -Pbuild-angular

        # Gerar o artefato de build (.jar)
      - name: Archive build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: java-angular-build - ${{ github.run_id}}
          path: target/*.jar

      - name: Login docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image Latest
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:latest

      - name: Build and push Docker image with tag
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ github.event.inputs.versao }}