name: Build Separados Java e Angular

on:
  workflow_dispatch:
    inputs:
      versao:
        description: 'Vers찾o do App'
        required: true
        default: '1.0.0'
        type: string

jobs:
  build_Java:
    runs-on: ubuntu-latest
    environment: BUILD

    steps:     
      - name: Checkout repository
        uses: actions/checkout@v3

      # Empacotar o c처digo-fonte para compartilhar entre jobs, para n찾o precisar fazer checkout novamente
      - name: Upload source code
        uses: actions/upload-artifact@v5
        with:
          name: source-code
          path: .
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
         
      - name: Build with Maven
        run: mvn -B clean package

      - name: Archive build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: java-angular-build - ${{ github.run_id}}
          path: target/*.jar

  build_Angular:
    runs-on: ubuntu-latest
    needs: build_Java # Indica que depende do job build_Java
        
    steps:

      # Baixa o c처digo-fonte do job anterior
      - name: Download source
        uses: actions/download-artifact@v4
        with:
          name: source-code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './src/frontend/web-todo/package-lock.json'
      
      - name: Install dependencies
        run: npm install
        working-directory: ./src/frontend/web-todo

      - name: Build Angular application
        run: npm run build -- --configuration production
        working-directory: ./src/frontend/web-todo

      - name: Archive Angular build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: angular-build - ${{ github.run_id}}